[project]
name = "backend-theory-of-information"
version = "0.1.0"
description = "My laboratories for subject \"theory of information\""
authors = [
    {name = "c3equalz",email = "dan.kovalev2013@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.115.8,<0.116.0)",
    "redis (>=5.2.1,<6.0.0)",
    "numpy (>=2.2.2,<3.0.0)",
    "dishka (>=1.4.2,<2.0.0)",
    "pydantic-settings (>=2.7.1,<3.0.0)",
    "uvicorn (>=0.34.0,<0.35.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
