# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-ast
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: end-of-file-fixer

-   repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets

-   repo: local
    hooks:
    -   id: lint
        name: Linter
        entry: just lint
        language: python
        types: [python]
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: mypy
        name: Mypy
        entry: just mypy
        language: python
        types: [python]
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: bandit
        name: bandit
        entry: just bandit
        language: python
        types: [python]
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: semgrep
        name: semgrep
        language: python
        entry: just semgrep
        types: [python]
        require_serial: true
        verbose: true
        pass_filenames: false

    -   id: zizmor
        name: zizmor
        language: python
        entry: just zizmor
        files: ^\.github\/workflows\/
        require_serial: true
        verbose: true
        pass_filenames: false